DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    hashed_password VARCHAR(100) NOT NULL,
    profile_pic VARCHAR(300),
    bio VARCHAR(1000),
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
